chore: fix error when building the listinapi image
Define a context to find files
Github Action crashes because of
Error: buildx failed with: ERROR: failed to solve: failed to compute cache key: failed to
calculate checksum of ref 6siri1cgvcqkb84vde7l39f20::2ykz5f6l7ay6eyd6fxzxy1uxe: "/Pipfile.lock": not found

feat: define hardcoded user:group for pricemap-python

chore: define default user:group on each containers